#pragma once
#define MODULE_NAME "TicTacToe"
#define MODULE_DOC "这个模块用于创建TicTacToe的游戏对象"
#define CLASS_NAME "TicTacToe.TicTacToe"
#define CLASS_DOC "TicTacToe game object"
#define CLASS_STATE_NAME "state"
#define CLASS_STATE_DOC "游戏的状态,先行号后列号,该属性只读"
#define CLASS_COUNT_NAME "count"
#define CLASS_COUNT_DOC "已用位置计数"
#define CLASS_FINAL_NAME "final"
#define CLASS_FINAL_DOC "最终结果,0为平局,-1为进行中,其他则为赢得游戏的玩家号+1"
#define CLASS_NEXT_NAME "next"
#define CLASS_NEXT_POSARG "posision"
#define CLASS_NEXT_NUMARG "playnum"
#define CLASS_NEXT_DOC "放棋子,前参数为位置(posision),后参为玩家号(playnum)为0或1,当终局后再进行操作会触发异常"
#define CLASS_CLEAR_NAME "clear"
#define CLASS_CLEAR_DOC "清理,重新开始一局游戏"
#define EXP_INDEX_USED "The Index is used"
#define EXP_INDEX_OVER "The Index out of range"
#define EXP_ARGS "Parameter format is not correct"
#define EXP_SETSTATE "Attribute 'state' is read-only"
#define EXP_SETCOUNT "Attribute 'count' is read-only"
#define EXP_SETFINAL "Attribute 'final' is read-only"
#define EXP_FINAL_NEXT "The game has ended"